### ISSUE TITLE
Missing logging.basicConfig() in train.py

### ISSUE THREAD

**Issue by blueclowd** [PhamQuocHuy1101/transfer-learning-template#14]
Hi sir, is there a way to enable the logging system cause the logging.basicConfig() in the __main__ doesn't seem to work.
I add the `logging.basicConfig(level=logging.INFO)` at the beginning of the script to enable the logging in train.py.

**Comment by PhamQuocHuy1101** [comment]
`  logging.basicConfig(filename=config.store.log, level=logging.INFO, filemode='w', format='%(levelname)s - %(message)s')`

The log store as the config.store.log, I put these codes in train.py

**Comment by blueclowd** [comment]
I see. I didn't aware that it export the result to external files rather than standard system output. Thanks
